Add support for PyTorch GPU memory limit
semi-technologies/t2v-transformers-models pull request #41
Opened 2023-01-03 23:55 UTC by kcm

Set CUDA_MEMORY_PCT between 0.0-1.0 inclusive to limit memory use in PyTorch. Defaults to 1.0.

This is useful, for example, in shared environments such as AWS's Virtual GPU

Addresses #39

2023-01-04 00:02 UTC, kcm commented
Test on local Linux running PyTorch 1.13.0 with CUDA12. Should be similar in EKS et al.

2023-01-05 12:46 UTC, StefanBogdan requested changes

2023-01-05 12:46 UTC, StefanBogdan commented on app.py
> +            logger.info(f"Invalid CUDA_MEMORY_PCT (should be between 0.0-1.0)")
lets make it a error log:
```python
logger.error("Invalid CUDA_MEMORY_PCT (should be between 0.0-1.0)")

2023-01-17 17:52 UTC, StefanBogdan approved these changes

2023-01-18 08:57 UTC, merged